services:
  - type: web
    name: fashion-marketplace
    env: docker
    region: oregon
    plan: starter
    buildCommand: docker build -t fashion-marketplace .

    envVars:
      - key: APP_NAME
        value: FashionMarketplace
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      
      # Database (TiDB)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
        
      # Mail (Resend)
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.resend.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: resend
      - key: MAIL_PASSWORD
        sync: false # User will input their Resend API Key here
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_FROM_ADDRESS
        value: onboarding@resend.dev
      - key: MAIL_FROM_NAME
        value: "Fashion Marketplace"
